### ISSUE TITLE
Is there any way to make it work with Magisk Delta + Zygisk Next module?

### ISSUE THREAD

**Issue by directentis1** [JingMatrix/ChromeXt#130] opened 2023-11-01 08:38 UTC
I'm using ChromeXt (latest) on LSPosed 1.9.2, using [Zygisk Next](https://github.com/Dr-TSNG/ZygiskNext/releases/tag/v4-0.8.1) instead of Magisk Zygisk, and using [Magisk Delta Canary](https://github.com/HuskyDG/magisk-files/releases/tag/0fe46c5a-delta) as root solution.

 But it seems, ChromeXt is not working, I don't notice any changes when opening Google Chrome.

 However, I have found an alternative way (workaround) to patch Chrome's apk file according to [your instructions](https://github.com/JingMatrix/ChromeXt#usage), overinstalling Chrome system using LSPosed's [Core patch Module](https://github.com/LSPosed/CorePatch) (helps overinstall files with different original signatures).

 But this method is really inconvenient because Chrome is often updated continuously,... and the Root + LSPosed based method will be more convenient, in the long run, and not only Google Chrome but most Chromium-based, like you instructed.

 Can you show me how to debug?

 Maybe Magisk Delta + Zygisk Next implemented something else (to hide the root more effectively) so it caused some LSPosed Modules, like ChromeXt, to not work (though others still work fine?)

**Comment by JingMatrix** [comment] 2023-11-01 08:56
As you have seen, the problem is more related to LSPosed or your root solution. In the ChromeXt part, I didn't make use of any features bounded to some specific implements of LSPosed or Magisk.

For you to debug, you may try
1. Install the debug version of ChromeXt: [ChromeXt-debug.zip](https://github.com/JingMatrix/ChromeXt/files/13225119/ChromeXt-debug.zip)
2. Check logs from the LSPosed manager
3. Use `adb logcat -s ChromeXt AndroidRunTime LSPosed` for more logs

You can paste your logs under this issue, I might be able to help with it.

**Comment by directentis1** [comment] 2023-11-01 18:39
@JingMatrix Here is my logs:
[chromext-debug-adb.log](https://github.com/JingMatrix/ChromeXt/files/13230679/chromext-debug.log)

[LSPosed_2023-11-02T01_29_39.138.zip](https://github.com/JingMatrix/ChromeXt/files/13230683/LSPosed_2023-11-02T01_29_39.138.zip)

Thank you in advance!

**Comment by directentis1** [comment] 2023-11-01 18:46
I tried (just curious) patched Android Web View, and after install it, some websites will show "Certificate Errors" when I click them from other apps that use Web View to access links inside them.

![](https://i.imgur.com/tM1YkFU.png)

It's strange when wikipedia doesn't show that, but youtube does.

**Comment by JingMatrix** [comment] 2023-11-01 18:53
The logs were not helpful, where only relevent info is:
```
11-02 01:30:35.233  5542  5542 I ChromeXt: Package: com.android.chrome, v118.0.5993.112
11-02 01:30:35.508  5542  5857 D LSPosed : LoadedApk#<init> starts: pkg=com.android.chrome, prc=com.android.chrome
11-02 01:30:35.509  5542  5857 D LSPosed : LoadedApk#<init> ends: /data/app/com.google.android.gms-BFpAIR9SZPCtRIDklU292Q==/base.apk: pkg=com.android.chrome, prc=com.android.chrome
11-02 01:30:39.987  6156  6156 D LSPosed : deoptimizing public android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader,java.lang.String,android.content.Context) throws java.lang.InstantiationException,java.lang.IllegalAccessException,java.lang.ClassNotFoundException: pkg=com.android.chrome, prc=com.android.chrome:privileged_process0
11-02 01:30:39.989  6156  6156 D LSPosed : deoptimizing public java.io.File android.app.ContextImpl.getSharedPreferencesPath(java.lang.String): pkg=com.android.chrome, prc=com.android.chrome:privileged_process0
11-02 01:30:39.989  6156  6156 D LSPosed : startBootstrapHook starts: isSystem = false
11-02 01:30:46.734  6927  6927 D LSPosed : deoptimizing public android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader,java.lang.String,android.content.Context) throws java.lang.InstantiationException,java.lang.IllegalAccessException,java.lang.ClassNotFoundException: pkg=com.google.android.webview, prc=com.google.android.webview:webview_service
```

Please disable all other modules, and try also other browsers such as `edge`. Make sure that LSPosed is **only** used for `ChromeXt`, and **only** the browser app is toggled on.

**Comment by directentis1** [comment] 2023-11-01 19:15
Hmm, seems like it's worked when I turnoff all another lsposed modules.
[LSPosed_2023-11-02T02_08_56.860.zip](https://github.com/JingMatrix/ChromeXt/files/13230925/LSPosed_2023-11-02T02_08_56.860.zip)
![Screenshot_20231102-020831_Edge](https://github.com/JingMatrix/ChromeXt/assets/128832114/a54e9ee1-3ca7-48c3-8ce4-9a9ffa25afce)
[chromext-debug.log](https://github.com/JingMatrix/ChromeXt/files/13230926/chromext-debug.log)

**Comment by JingMatrix** [comment] 2023-11-01 19:18
Congrat! I close this issue now.

If you find out which modules are blocking the funtionality of ChromeXt, you may continue to share your discovery here!

**Closed by JingMatrix** 2023-11-01 19:18 UTC

**Comment by directentis1** [comment] 2023-11-01 19:19
Brave also working, I just tested it.

Thanks, maybe I'll need some trial-and-errors to find the problem ;)

**Comment by directentis1** [comment] 2023-11-02 01:48
I accidentally enabled https://github.com/5ec1cff/StethoX a while ago on some apps, and it caused a conflict with Chromext.
 FYI.
