### ISSUE TITLE
Can't delete Userscript in the Fron End

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#7] opened 2022-12-20 10:33 UTC
the scripts that's installed can't be deleted through the front end, sometimes i can delete and sometimes this happens
Here's a screen recording of it
https://photos.app.goo.gl/SpMVg8E7z79GTb7y5

**Comment by JingMatrix** [comment] 2022-12-20 12:09
I can confirm that this is a bug.

I was  debugging it before you made the issue here.
I was also very confused what happenned because the bug just disappeared sometimes.
Could you give me the installation url of the problematic script?
I will try to figure out what is wrong

At the end, I will give a `delete all` button since it was really impossible for me to delete some script.

**Comment by JingMatrix** [comment] 2022-12-20 12:17
I see that your problematic script was the [invalid one](https://raw.githubusercontent.com/FarisHijazi/Rarbg-Enhancer-UserScript/master/Rarbg-Enhancer-UserScript.user.js) that couldn't be installed.
Maybe you managed to install it, please then wait for the `deleta all` button to appear later.

**Comment by MohamadBayz** [comment] 2022-12-20 12:31
Yes it's the invalid one.i just put // ==UserScript== in the first line and that happened although this happened last night too when i installed this script alongside some other script that they were all Scripts for one website
https://greasyfork.org/scripts/373230-1337x-magnet-torrent-links-everywhere/code/1337X%20-%20MagnetTorrent%20links%20everywhere.user.js
The script didn't work although all the API were supported by ChromeXT

**Comment by MohamadBayz** [comment] 2022-12-20 12:36
Weirdly i installed all these four scripts together but none of them worked beside the fact that there API Was listed in the supported API and then i couldn't delete them
https://greasyfork.org/scripts/373230-1337x-magnet-torrent-links-everywhere/code/1337X%20-%20MagnetTorrent%20links%20everywhere.user.js

https://greasyfork.org/scripts/421635-1337x-convert-torrent-timestamps-to-relative-format/code/1337X%20-%20convert%20torrent%20timestamps%20to%20relative%20format.user.js

https://greasyfork.org/scripts/29467-1337x-subtitle-download-links-to-tv-and-movie-torrents/code/1337X%20-%20Subtitle%20download%20links%20to%20TV%20and%20Movie%20torrents.user.js

https://greasyfork.org/scripts/33379-1337x-torrent-page-improvements/code/1337x%20-%20Torrent%20page%20improvements.user.js

**Comment by JingMatrix** [comment] 2022-12-20 13:23
The delete bug is fixed in ca4d482f250f034b17d8b0937c6030d6a15c79b3, please install the latest update from GitHub Action.

**Comment by JingMatrix** [comment] 2022-12-20 13:26
> Yes it's the invalid one.i just put // ==UserScript== in the first line and that happened although this happened last night too when i installed this script alongside some other script that they were all Scripts for one website https://greasyfork.org/scripts/373230-1337x-magnet-torrent-links-everywhere/code/1337X%20-%20MagnetTorrent%20links%20everywhere.user.js The script didn't work although all the API were supported by ChromeXT

That is because the `@include` field is problematic, it doesn't conform to [the standard by Google](https://developer.chrome.com/docs/extensions/mv2/match_patterns/).
By the way, it is better to ask different questions in new issues.

**Closed by JingMatrix** 2022-12-20 13:26 UTC
Labels: bug

**Comment by MohamadBayz** [comment] 2022-12-20 16:00
> That is because the `@include` field is problematic, it doesn't conform to [the standard by Google](https://developer.chrome.com/docs/extensions/mv2/match_patterns/). By the way, it is better to ask different questions in new issues.

Basically the script needs an update for manifest v3, I didn't want to bother you with all these questions
