### ISSUE TITLE
Page menu crash [Android 10]

### ISSUE THREAD

**Issue by inguna87** [JingMatrix/ChromeXt#37] opened 2023-04-23 09:02 UTC
Hi, do you mind sharing the latest debug version please? I am asking because only debug version is working properly with non-split Chrome 111.0.5563.116. I am using one from here https://github.com/JingMatrix/ChromeXt/files/11071645/debug_version.zip but it is quite outdated and I would like to try new features. Thanks a lot in advance

**Comment by JingMatrix** [comment] 2023-04-23 09:09
Hi!
Sharing debug version is definitely not a good way to update, so could you please try the following first?
I am quite sure the bug there was fixed later.
Could you try the latest build from [Github Action](https://github.com/JingMatrix/ChromeXt/actions) and tell me if it works for you?
You need to uninstall your debug version first since the signature is different.
If not, I will give you a debug version.

**Comment by inguna87** [comment] 2023-04-23 09:19
Thanks, I have tried all the latest Github action versions but chrome force closes every time I press 3 dots. I will attach log in a few minutes

**Comment by JingMatrix** [comment] 2023-04-23 09:36
It is the same bug as #34, and I don't know the reason yet.
I am not sure a debug version will work.
But if you are glad to try, here it is:
[debug_version.zip](https://github.com/JingMatrix/ChromeXt/files/11303335/debug_version.zip)

If it still doesn't work, please share the log again. It will be useful for me to find out the bug.

**Comment by inguna87** [comment] 2023-04-23 09:45
I have tried the latest debug version and chrome force closes with the same error in lsposed when I press 3 dots. I will use debug version you shared in March for now.  Thank you

**Comment by JingMatrix** [comment] 2023-04-23 09:47
Please share the log for the lastest debug version, which will be useful for me.

**Comment by inguna87** [comment] 2023-04-23 09:54
Oneplus 7 Pro, Android 10

**Comment by JingMatrix** [comment] 2023-04-23 09:58
I hope this is not bothering you if you wish to improve this project.
Are you sure the log came from the debug version?
The debug version provides more log that would be useful for me.
The log you provided seems come from a release version.

**Comment by JingMatrix** [comment] 2023-04-23 12:49
I cannot reproduce this bug on my phone, maybe because I am using Andorid 13. 
It is really strange, the 'three dots menu' problem might be a bug of LSPosed.
I have no idea why the old debug doesn't have this bug.

As for the developper tools menu, it might be that you are using multiple Chrome versions on your phone.
One needs to close other Chrome instance if he wants to use the native DevTools.

**Comment by JingMatrix** [comment] 2023-04-23 12:56
Do you know how to connect your phone with a USB wire and use `adb` command in your computer?
 If that is the case, please use the lastest debug version and run
```
adb logcat -s ChromeXt:D
```
from your computer.
It will show useful debug logs for me.

**Comment by inguna87** [comment] 2023-04-23 13:48
>
> As for the developper tools menu, it might be that you are using multiple Chrome versions on your phone. One needs to close other Chrome instance if he wants to use the native DevTools.

You are right about this issue. My default browser is Kiwi, as soon as I force stopped Kiwi I could use developer tools in Chrome. That's one issue sorted.


I will post adb logs here a bit later. Thanks

**Comment by JingMatrix** [comment] 2023-04-23 22:20
The bug is found now, I need some time to fix it.

**Comment by JingMatrix** [comment] 2023-04-23 23:18
The bug is fixed now, please try the lastest build from [Github Action](https://github.com/JingMatrix/ChromeXt/actions)

**Closed by JingMatrix** 2023-04-23 23:18 UTC
Labels: bug
