### ISSUE TITLE
update edge to 114.0.1823.61，ChromeXt is not installed

### ISSUE THREAD

**Issue by soulpursuit** [JingMatrix/ChromeXt#58] opened 2023-06-26 07:47 UTC
in edge：114.0.1823.61
no run

**Comment by JingMatrix** [comment] 2023-06-26 07:53
Duplicate of #57 , it is fixed. Please pick the apk from GitHub Action, or the release page (I updated it).

**Closed by JingMatrix** 2023-06-26 07:53 UTC
