### ISSUE TITLE
Access to the file was denied

### ISSUE THREAD

**Issue by cod-md** [JingMatrix/ChromeXt#29] opened 2023-04-03 20:08 UTC
This happens when I activate chromext
I am using chrome v108
And to activate chromext in the firstplace i had to clear chrome data 
![Screenshot_20230403-230406133](https://user-images.githubusercontent.com/92212094/229615734-54d89ced-3ca5-43f5-85f2-0b4b8af39bdf.jpg)

**Comment by JingMatrix** [comment] 2023-04-03 20:13
Do you have any ralated logs in your xposed framework?
By the way, would you mind to update your Chrome to v111?

**Comment by cod-md** [comment] 2023-04-03 20:27
![Screenshot_20230403-232513529](https://user-images.githubusercontent.com/92212094/229619519-1434e77b-9819-47a7-9b47-9b752a945b71.jpg)
?
When i updated to v111 through play store
 it stopped working
![Screenshot_20230403-232308321](https://user-images.githubusercontent.com/92212094/229619675-34e02823-5854-4d16-8e74-707c6154b082.jpg)

**Comment by JingMatrix** [comment] 2023-04-03 20:28
The latest version is here: [Github Action](https://github.com/JingMatrix/ChromeXt/actions)

**Comment by cod-md** [comment] 2023-04-03 20:34
ChromeXt worked but the same error Access to the file was denied

**Comment by cod-md** [comment] 2023-04-03 20:37
By the way, did you know that adguard has the same feature 
![Screenshot_20230403-233534638](https://user-images.githubusercontent.com/92212094/229621961-b1111aa2-3dd4-487c-ac73-42b4e98bc6c9.jpg)

**Comment by cod-md** [comment] 2023-04-03 20:47
I didn't understand what you mean
But adguard userscripts works well

**Comment by cod-md** [comment] 2023-04-03 20:54
An example


Uploading 23-04-03-23-52-52.mp4…

**Comment by cod-md** [comment] 2023-04-03 20:56
It is for all files in chromext

As for Adguard With root it can do the same as chromext in chrome

**Comment by JingMatrix** [comment] 2023-04-03 20:59
I cannot reproduce your problem. Does it still present if you restart your phone?
Could you show me the logs from your Xposed framework?

**Comment by cod-md** [comment] 2023-04-03 20:59
https://user-images.githubusercontent.com/92212094/229626167-a18e4553-908a-4870-87fa-c3415b0ec243.mp4

**Comment by JingMatrix** [comment] 2023-04-03 21:07
> As for Adguard With root it can do the same as chromext in chrome

That one isn't open source. I don't trust any application requiring root but not open source.

**Comment by JingMatrix** [comment] 2023-04-03 21:15
It might be a problem caused by using Adguard together with ChromeXt, I am not sure.
There is no code of ChromeXt stopping users from opening file.
People used to download scripts and install them without reporting any similar issues.
The situation might be more complicated in your phone, given that your AdGuard is very powerful.

**Comment by cod-md** [comment] 2023-04-03 21:35
https://user-images.githubusercontent.com/92212094/229632817-e249b112-4887-4e96-b19c-6afa5965811b.mp4

Adguard is turned off

**Comment by JingMatrix** [comment] 2023-04-03 21:51
Okay, I get it now after seeing the video, thanks for that.
It is a problem of ChromeXt, I will fix it soon.
Meanwhile, your chrome is still not the latest, please consider update it.

**Comment by cod-md** [comment] 2023-04-03 21:54
i updated to v111 then returned to v108 just to try and it's the same

**Comment by JingMatrix** [comment] 2023-04-03 21:59
What is your Android version? I think this might be a Android storage API problem.
It doesn't matter the version, I mention just as a remind, you can ignore it.

**Comment by JingMatrix** [comment] 2023-04-03 23:44
Now the bug is fixed, please test the lastest build from [Github Action](https://github.com/JingMatrix/ChromeXt/actions)

**Comment by cod-md** [comment] 2023-04-04 10:49
It worked !
You're amazing =)
Thanks .

**Comment by cod-md** [comment] 2023-10-08 11:19
I face the same issue after updating to 
Chromext 3.8.0
![Screenshot_20231008-141416999](https://github.com/JingMatrix/ChromeXt/assets/92212094/323bfb24-2829-4b79-a147-9be60736556d)

Chrome  116
Android 10

**Comment by JingMatrix** [comment] 2023-10-08 13:41
This should be fixed now.
I somehow forgot that your device was kind of different than others.

**Closed** 2023-10-08 13:40 UTC
