### ISSUE TITLE
JingMatrix/LSPatch not working for Soul browser

### ISSUE THREAD

**Issue by luxysiv** [JingMatrix/ChromeXt#78] opened 2023-07-20 00:50 UTC
I have read an issue said fully support Soul browser but I can't patch it on Manager. Please check it

**Comment by JingMatrix** [comment] 2023-07-20 06:15
Can you post your patching logs here?

**Comment by JingMatrix** [comment] 2023-07-20 06:52
Currently, for Soul browser, [the original LSPatch](https://github.com/LSPosed/LSPatch) project works.
I will fix [JingMatrix/LSPatch](https://github.com/JingMatrix/LSPatch) in the future.
This is not a bug of ChromeXt, so I close it here.

**Closed by JingMatrix** 2023-07-20 06:52 UTC
Labels: bug

**Comment by JingMatrix** [comment] 2023-07-20 14:27
The related bug in `JingMatrix/LSPatch`, you should be able to use it.

Note: if you patch the `Soul Browser` installed from google play using the manager app, you need [Shizuku](https://github.com/RikkaApps/Shizuku) to help you install the patched split APKs.
