### ISSUE TITLE
on MS Edge ChromeXt often doesn't work

### ISSUE THREAD

**Issue by hole-orig** [JingMatrix/ChromeXt#178] opened 2024-07-10 02:05 UTC
Recently, on MS Edge ChromeXt often doesn't work,my environment.
(Probably since beta support for extensions.)

※I believe this is an issue with Edge,or my environment.
So this is a report, not a correction request.
※Sorry if this is a wrong report.

**Comment by JingMatrix** [comment] 2024-07-23 22:58
Cannot reproduce and no detailed descriptions provided, so I close it.
You may reopen it when you find necessary.

**Closed by JingMatrix** 2024-07-23 22:58 UTC
