### ISSUE TITLE
Crash on Chrome 121.0.6167.102

### ISSUE THREAD

**Issue by NagatoException** [JingMatrix/ChromeXt#148] opened 2024-02-02 09:34 UTC
log ：https://paste.evolution-x.org/VUzrc2

disable this module issue is fixed

**Comment by JingMatrix** [comment] 2024-02-02 09:47
It is a duplicate of #145, which is already fixed. Please use the latest ChromeXt from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions).

**Closed** 2024-02-02 09:48 UTC
Labels: duplicate
