### ISSUE TITLE
Page menu crash [Android 8.1]

### ISSUE THREAD

**Issue by AbdullahM0hamed** [JingMatrix/ChromeXt#34] opened 2023-04-18 02:13 UTC
System: Android 8.1, LSPosed (Zygisk), Latest Magisk (26.1)

Relevant log stuff:

<details>
  <summary>LOG</summary>
[ 2023-04-18T02:52:41.645    10090:  5787:  5787 I/LSPosed-Bridge  ]   Loading class org.matrix.chromext.MainHook
[ 2023-04-18T02:52:41.838    10090:  5787:  5787 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.ChromeTabbedActivity" on path: DexPathList[[zip file "/data/app/com.android.chrome-WEa_CdfEMQ5B0ogZsZN31g==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-WEa_CdfEMQ5B0ogZsZN31g==/lib/arm, /data/app/com.android.chrome-WEa_CdfEMQ5B0ogZsZN31g==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.matrix.chromext.MainHook.handleLoadPackage(Unknown Source:101)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:980)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2420)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5996)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
[ 2023-04-18T02:52:57.952    10090:  6949:  6949 I/LSPosed-Bridge  ] Loading module org.matrix.chromext from /data/app/org.matrix.chromext-_vW-2lai8-H6o19zX-B_9A==/base.apk
[ 2023-04-18T02:52:57.963    10090:  6949:  6949 I/LSPosed-Bridge  ]   Loading class org.matrix.chromext.MainHook
[ 2023-04-18T02:52:58.187    10090:  6949:  6949 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.ChromeTabbedActivity" on path: DexPathList[[zip file "/data/app/com.android.chrome-WEa_CdfEMQ5B0ogZsZN31g==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-WEa_CdfEMQ5B0ogZsZN31g==/lib/arm, /data/app/com.android.chrome-WEa_CdfEMQ5B0ogZsZN31g==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.matrix.chromext.MainHook.handleLoadPackage(Unknown Source:101)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:980)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2420)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5996)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
</details>

The issue seems to be:

`
java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.ChromeTabbedActivity"`

But I have confirmed that the chrome apk does in fact have `org.chromium.chrome.browser.ChromeTabbedActivity` present. Any ideas?

**Comment by JingMatrix** [comment] 2023-04-18 19:04
Chrome V112 apk is now available online.
Please update to v112 first to see if it becomes better.

The issue might be caused by your Andorid version 8.1. 
Is it possible for you to update your Android system?

**Comment by JingMatrix** [comment] 2023-04-23 23:19
The bug is fixed now, please try the lastest build from [Github Action](https://github.com/JingMatrix/ChromeXt/actions).

**Closed by JingMatrix** 2023-04-23 23:19 UTC
Labels: bug
